# This workflow will delete the respective fork branch when a PR authored by 'jenkins-is-staging' is merged/closed.
name: Fork Branch Deleter

on:
  pull_request:
    types: [ closed ]

jobs:
  build:
    # Check whether the PR was authored by 'wso2-jenkins-bot'
    if: github.event.pull_request.head.repo.owner.login == 'Wathsara'
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.PAT }}
    steps:
      # Check out the asgardeo-product fork of 'wso2-jenkins-bot' user
      - uses: actions/checkout@v2
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          fetch-depth: 0
          token: ${{env.GITHUB_TOKEN}}

      - name: Delete Fork Branch of wso2-jenkins-bot
        run: git push -d origin ${{ github.event.pull_request.head.ref }}
